/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EwhachainBank } from "./EwhachainBank";

export { EwhachainBank__factory } from "./factories/EwhachainBank__factory";
